In [1]:
import numpy as np
import pandas as pd
# The requests library simplifies the process of making http requests
import requests
import os

# Exercise Instructions 

The end result of this exercise should be a file named acquire.py.

1. Using the code from the lesson as a guide and the REST API from https://python.zgulde.net/api/v1/items as we did in the lesson, create a dataframe named items that has all of the data for items.

2. Do the same thing, but for stores (https://python.zgulde.net/api/v1/stores)

3. Extract the data for sales (https://python.zgulde.net/api/v1/sales). There are a lot of pages of data here, so your code will need to be a little more complex. Your code should continue fetching data from the next page until all of the data is extracted.

4. Save the data in your files to local csv files so that it will be faster to access in the future.

5. Combine the data from your three separate dataframes into one large dataframe.

6. Acquire the Open Power Systems Data for Germany, which has been rapidly expanding its renewable energy production in recent years. The data set includes country-wide totals of electricity consumption, wind power production, and solar power production for 2006-2017. You can get the data here: https://raw.githubusercontent.com/jenfly/opsd/master/opsd_germany_daily.csv

7. Make sure all the work that you have done above is reproducible. That is, you should put the code above into separate functions in the acquire.py file and be able to re-run the functions and get the same data.

## Exercise 1

In [3]:
## Intial Set-Up
domain = 'https://python.zgulde.net'
endpoint = '/api/v1/items'
items = []

# For each page -- until next page is None
url = domain + endpoint
response = requests.get(url)
data = response.json()
items.extend(data['payload']['items'])
# update the endpoint
endpoint = data['payload']['next_page']

In [4]:
data['payload'].keys()

dict_keys(['items', 'max_page', 'next_page', 'page', 'previous_page'])

In [5]:
# For each page -- until next page is None
url = domain + endpoint
response = requests.get(url)
data = response.json()
items.extend(data['payload']['items'])
# update the endpoint
endpoint = data['payload']['next_page']

In [6]:
# For each page -- until next page is None
url = domain + endpoint
response = requests.get(url)
data = response.json()
items.extend(data['payload']['items'])
# update the endpoint
endpoint = data['payload']['next_page']

In [7]:
type(endpoint)

NoneType

In [8]:
data['payload']['max_page']

3

In [9]:
df = pd.DataFrame(items)
df

,item_brand,item_id,item_name,item_price,item_upc12,item_upc14
0,Riceland,1,Riceland American Jazmine Rice,0.84,35200264013,35200264013
1,Caress,2,Caress Velvet Bliss Ultra Silkening Beauty Bar...,6.44,11111065925,11111065925
2,Earths Best,3,Earths Best Organic Fruit Yogurt Smoothie Mixe...,2.43,23923330139,23923330139
3,Boars Head,4,Boars Head Sliced White American Cheese - 120 Ct,3.14,208528800007,208528800007
4,Back To Nature,5,Back To Nature Gluten Free White Cheddar Rice ...,2.61,759283100036,759283100036
5,Sally Hansen,6,Sally Hansen Nail Color Magnetic 903 Silver El...,6.93,74170388732,74170388732
6,Twinings Of London,7,Twinings Of London Classics Lady Grey Tea - 20 Ct,9.64,70177154004,70177154004
7,Lea & Perrins,8,Lea & Perrins Marinade In-a-bag Cracked Pepper...,1.68,51600080015,51600080015
8,Van De Kamps,9,Van De Kamps Fillets Beer Battered - 10 Ct,1.79,19600923015,19600923015
9,Ahold,10,Ahold Cocoa Almonds,3.17,688267141676,688267141676
10,Honest Tea,11,Honest Tea Peach White Tea,3.93,657622604842,657622604842
11,Mueller,12,Mueller Sport Care Basic Support Level Medium ...,8.40,74676640211,74676640211
12,Garnier Nutritioniste,13,Garnier Nutritioniste Moisture Rescue Fresh Cl...,6.47,603084234561,603084234561
13,Pamprin,14,Pamprin Maximum Strength Multi-symptom Menstru...,7.54,41167300121,41167300121
14,Suave,15,Suave Naturals Moisturizing Body Wash Creamy T...,9.11,79400847201,79400847201
15,Burts Bees,16,Burts Bees Daily Moisturizing Cream Sensitive,5.17,792850014008,792850014008
16,Ducal,17,Ducal Refried Red Beans,1.16,88313590791,88313590791
17,Scotch,18,Scotch Removable Clear Mounting Squares - 35 Ct,4.39,21200725340,21200725340
18,Careone,19,Careone Family Comb Set - 8 Ct,0.74,41520035646,41520035646
19,Usda Produce,20,Plums Black,5.62,204040000000,204040000000
20,Doctors Best,21,Doctors Best Best Curcumin C3 Complex 1000mg T...,8.09,753950001954,753950001954
21,Betty Crocker,22,Betty Crocker Twin Pack Real Potatoes Scallope...,7.31,16000288829,16000288829
22,Reese,23,Reese Mandarin Oranges Segments In Light Syrup,1.78,70670009658,70670009658
23,Smart Living,24,Smart Living Charcoal Lighter Fluid,5.34,688267084225,688267084225
24,Hood,25,Hood Latte Iced Coffee Drink Vanilla Latte,2.43,44100117428,44100117428
25,Triaminic,26,Triaminic Syrup Night Time Cold & Cough Grape 4oz,0.98,300436344045,300436344045
26,Morton,27,Morton Kosher Salt Coarse,6.01,24600017008,24600017008
27,Usda Produce,28,Guava,7.52,719175900007,719175900007
28,Heinz,29,Heinz Tomato Ketchup - 2 Ct,8.65,13000001038,13000001038
29,Petmate,30,Petmate Booda Bones Steak Bacon & Chicken Flav...,8.39,723503568678,723503568678
30,Zhenas Gypsy Tea,31,Zhenas Gypsy Tea Herbal Red Tea Sachets Fire L...,4.21,652790100226,652790100226
31,Barefoot,32,Barefoot Pinot Grigio 187,0.68,8500004528,8500004528
32,The First Years,33,Tomy The First Years Gumdrop Orthodontic Pacif...,6.52,71463060078,71463060078
33,Halls,34,Halls Menthol Cough Suppresant/oral Anesthetic...,4.17,312546628694,312546628694
34,Natures Way,35,Natures Way Forskohlii - 60 Ct,5.19,33674100066,33674100066
35,Deerfields Gluten Free,36,Rice Bran Gluten Free Dinner Rolls Plain,7.95,610358991525,610358991525
36,Nakano,37,Nakano Seasoned Rice Vinegar Original,9.59,73575295003,73575295003
37,Sundown Naturals,38,Sundown Naturals Essential Electrolytes Tropic...,3.45,30768540548,30768540548
38,Munchies,39,Munchies Sandwich Crackers Cheddar Cheese On G...,9.02,28400029254,28400029254
39,Amys,40,Amys Light & Lean Spaghetti Italiano,0.60,42272008063,42272008063
40,P.f. Changs,41,P.f. Changs Home Menu Meal For Two Beef With B...,5.62,31000670016,31000670016
41,Moms Best Naturals,42,Moms Best Naturals Cereal Toasted Cinnamon Squ...,2.97,883978129115,883978129115
42,Ferrara,43,Ferrara Vanilla Syrup,8.40,71403000379,71403000379
43,Elmers,44,Elmers Board Mate Dual Tip Glue Pen,7.06,26000001403,26000001403
44,Kelloggs,45,Kelloggs Disney Pixar Cars 2 Cereal,4.40,38000542237,38000542237
45,Mama Marys,46,Pizza Sauce,4.65,35457770664,35457770664
46,Bear Naked,47,Bear Naked Fit Almond Crisp 100 Percent Natura...,7.38,884623708976,884623708976
47,Dove,48,Dove Men + Care Antiperspirant Deodorant Cool ...,3.72,79400271631,79400271631
48,Easy-off,49,Easy-off Oven Cleaner Lemon Scent,9.54,62338879772,62338879772
49,Choice,50,Choice Organic Teas Black Tea Classic Black - ...,5.20,47445919221,47445919221

In [26]:
# Create a function that replicates this

def get_items(use_cache = True):
    '''
    This function takes in no arguments. It firsts checks if 'items.csv' exists, and if does, it returns a dataframe
    using this file. If the file does not exist it gathers the data using an API, creates a dataframe and caches it as 
    as a .csv file, then returns the dataframe.
    '''
    filename = 'items.csv'

    #Check for the csv cache
    if os.path.isfile(filename) and use_cache:
        print('Using cached csv...')
        return pd.read_csv(filename)

    else:
        #Gather data from the first page
        print('Gathering data using API...')
        domain = 'https://python.zgulde.net'
        endpoint = '/api/v1/items'
        items = []
        while True:
            url = domain + endpoint
            response = requests.get(url)
            data = response.json()
            print(f'\rGetting page {data["payload"]["page"]} of {data["payload"]["max_page"]}: {url}', end='')
            items.extend(data['payload']['items'])
            endpoint = data['payload']['next_page']
            if endpoint is None:
                break

        # Now cache the dataframe as a .csv
        df = pd.DataFrame(items)
        df.to_csv('items.csv', index = False)

        return df

In [27]:
#Test function
get_items()

Gathering data using API...
Getting page 3 of 3: https://python.zgulde.net/api/v1/items?page=3

,item_brand,item_id,item_name,item_price,item_upc12,item_upc14
0,Riceland,1,Riceland American Jazmine Rice,0.84,35200264013,35200264013
1,Caress,2,Caress Velvet Bliss Ultra Silkening Beauty Bar...,6.44,11111065925,11111065925
2,Earths Best,3,Earths Best Organic Fruit Yogurt Smoothie Mixe...,2.43,23923330139,23923330139
3,Boars Head,4,Boars Head Sliced White American Cheese - 120 Ct,3.14,208528800007,208528800007
4,Back To Nature,5,Back To Nature Gluten Free White Cheddar Rice ...,2.61,759283100036,759283100036
5,Sally Hansen,6,Sally Hansen Nail Color Magnetic 903 Silver El...,6.93,74170388732,74170388732
6,Twinings Of London,7,Twinings Of London Classics Lady Grey Tea - 20 Ct,9.64,70177154004,70177154004
7,Lea & Perrins,8,Lea & Perrins Marinade In-a-bag Cracked Pepper...,1.68,51600080015,51600080015
8,Van De Kamps,9,Van De Kamps Fillets Beer Battered - 10 Ct,1.79,19600923015,19600923015
9,Ahold,10,Ahold Cocoa Almonds,3.17,688267141676,688267141676
10,Honest Tea,11,Honest Tea Peach White Tea,3.93,657622604842,657622604842
11,Mueller,12,Mueller Sport Care Basic Support Level Medium ...,8.40,74676640211,74676640211
12,Garnier Nutritioniste,13,Garnier Nutritioniste Moisture Rescue Fresh Cl...,6.47,603084234561,603084234561
13,Pamprin,14,Pamprin Maximum Strength Multi-symptom Menstru...,7.54,41167300121,41167300121
14,Suave,15,Suave Naturals Moisturizing Body Wash Creamy T...,9.11,79400847201,79400847201
15,Burts Bees,16,Burts Bees Daily Moisturizing Cream Sensitive,5.17,792850014008,792850014008
16,Ducal,17,Ducal Refried Red Beans,1.16,88313590791,88313590791
17,Scotch,18,Scotch Removable Clear Mounting Squares - 35 Ct,4.39,21200725340,21200725340
18,Careone,19,Careone Family Comb Set - 8 Ct,0.74,41520035646,41520035646
19,Usda Produce,20,Plums Black,5.62,204040000000,204040000000
20,Doctors Best,21,Doctors Best Best Curcumin C3 Complex 1000mg T...,8.09,753950001954,753950001954
21,Betty Crocker,22,Betty Crocker Twin Pack Real Potatoes Scallope...,7.31,16000288829,16000288829
22,Reese,23,Reese Mandarin Oranges Segments In Light Syrup,1.78,70670009658,70670009658
23,Smart Living,24,Smart Living Charcoal Lighter Fluid,5.34,688267084225,688267084225
24,Hood,25,Hood Latte Iced Coffee Drink Vanilla Latte,2.43,44100117428,44100117428
25,Triaminic,26,Triaminic Syrup Night Time Cold & Cough Grape 4oz,0.98,300436344045,300436344045
26,Morton,27,Morton Kosher Salt Coarse,6.01,24600017008,24600017008
27,Usda Produce,28,Guava,7.52,719175900007,719175900007
28,Heinz,29,Heinz Tomato Ketchup - 2 Ct,8.65,13000001038,13000001038
29,Petmate,30,Petmate Booda Bones Steak Bacon & Chicken Flav...,8.39,723503568678,723503568678
30,Zhenas Gypsy Tea,31,Zhenas Gypsy Tea Herbal Red Tea Sachets Fire L...,4.21,652790100226,652790100226
31,Barefoot,32,Barefoot Pinot Grigio 187,0.68,8500004528,8500004528
32,The First Years,33,Tomy The First Years Gumdrop Orthodontic Pacif...,6.52,71463060078,71463060078
33,Halls,34,Halls Menthol Cough Suppresant/oral Anesthetic...,4.17,312546628694,312546628694
34,Natures Way,35,Natures Way Forskohlii - 60 Ct,5.19,33674100066,33674100066
35,Deerfields Gluten Free,36,Rice Bran Gluten Free Dinner Rolls Plain,7.95,610358991525,610358991525
36,Nakano,37,Nakano Seasoned Rice Vinegar Original,9.59,73575295003,73575295003
37,Sundown Naturals,38,Sundown Naturals Essential Electrolytes Tropic...,3.45,30768540548,30768540548
38,Munchies,39,Munchies Sandwich Crackers Cheddar Cheese On G...,9.02,28400029254,28400029254
39,Amys,40,Amys Light & Lean Spaghetti Italiano,0.60,42272008063,42272008063
40,P.f. Changs,41,P.f. Changs Home Menu Meal For Two Beef With B...,5.62,31000670016,31000670016
41,Moms Best Naturals,42,Moms Best Naturals Cereal Toasted Cinnamon Squ...,2.97,883978129115,883978129115
42,Ferrara,43,Ferrara Vanilla Syrup,8.40,71403000379,71403000379
43,Elmers,44,Elmers Board Mate Dual Tip Glue Pen,7.06,26000001403,26000001403
44,Kelloggs,45,Kelloggs Disney Pixar Cars 2 Cereal,4.40,38000542237,38000542237
45,Mama Marys,46,Pizza Sauce,4.65,35457770664,35457770664
46,Bear Naked,47,Bear Naked Fit Almond Crisp 100 Percent Natura...,7.38,884623708976,884623708976
47,Dove,48,Dove Men + Care Antiperspirant Deodorant Cool ...,3.72,79400271631,79400271631
48,Easy-off,49,Easy-off Oven Cleaner Lemon Scent,9.54,62338879772,62338879772
49,Choice,50,Choice Organic Teas Black Tea Classic Black - ...,5.20,47445919221,47445919221

## Exercise 2

In [19]:
domain = 'https://python.zgulde.net'
endpoint = '/api/v1/stores'

while endpoint != None:
    stores = []
    url = domain + endpoint
    data = requests.get(url).json()
    items.extend(data['payload']['stores'])
    endpoint = data['payload']['next_page']
    df2 = pd.DataFrame(stores)

In [20]:
# Create a similar function to my items function for stores

def get_stores(use_cache = True):
    '''
    This function takes in no arguments. It firsts checks if 'stores.csv' exists, and if does, it returns a dataframe
    using this file. If the file does not exist it gathers the data using an API, creates a dataframe and caches it as 
    as a .csv file, then returns the dataframe.
    '''
    filename = 'stores.csv'

    #Check for the csv cache
    if os.path.isfile(filename) and use_cache:
        print('Using cached csv...')
        return pd.read_csv(filename)

    else:
        #Gather data from the first page
        print('Gathering data using API...')
        domain = 'https://python.zgulde.net'
        endpoint = '/api/v1/stores'
        items = []
        while endpoint is not None:
            url = domain + endpoint
            response = requests.get(url)
            data = response.json()
            print(f'\rGetting page {data["payload"]["page"]} of {data["payload"]["max_page"]}: {url}', end='')
            items.extend(data['payload']['stores'])
            endpoint = data['payload']['next_page']

        # Now cache the dataframe as a .csv
        df = pd.DataFrame(items)
        df.to_csv('stores.csv', index = False)

        return df

In [21]:
#Test it out 
get_stores()

Gathering data using API...
Getting page 1 of 1: https://python.zgulde.net/api/v1/stores

             store_address   store_city  store_id store_state store_zipcode
0   12125 Alamo Ranch Pkwy  San Antonio         1          TX         78253
1         9255 FM 471 West  San Antonio         2          TX         78251
2  2118 Fredericksburg Rdj  San Antonio         3          TX         78201
3          516 S Flores St  San Antonio         4          TX         78204
4          1520 Austin Hwy  San Antonio         5          TX         78218
5       1015 S WW White Rd  San Antonio         6          TX         78220
6   12018 Perrin Beitel Rd  San Antonio         7          TX         78217
7      15000 San Pedro Ave  San Antonio         8          TX         78232
8       735 SW Military Dr  San Antonio         9          TX         78221
9     8503 NW Military Hwy  San Antonio        10          TX         78231

## Exercise 3

In [25]:
# Create a similar function to my items function for stores

def get_sales(use_cache = True):
    '''
    This function takes in no arguments. It firsts checks if 'sales.csv' exists, and if does, it returns a dataframe
    using this file. If the file does not exist it gathers the data using an API, creates a dataframe and caches it as 
    as a .csv file, then returns the dataframe.
    '''
    filename = 'sales.csv'

    #Check for the csv cache
    if os.path.isfile(filename) and use_cache:
        print('Using cached csv...')
        return pd.read_csv(filename)

    else:
        #Gather data from the first page
        print('Gathering data using API...')
        domain = 'https://python.zgulde.net'
        endpoint = '/api/v1/sales'
        items = []
        while endpoint is not None:
            url = domain + endpoint
            response = requests.get(url)
            data = response.json()
            print(f'\rGetting page {data["payload"]["page"]} of {data["payload"]["max_page"]}: {url}', end='')
            items.extend(data['payload']['sales'])
            endpoint = data['payload']['next_page']

        # Now cache the dataframe as a .csv
        df = pd.DataFrame(items)
        df.to_csv('sales.csv', index = False)

        return df

In [23]:
# Test it
get_sales()

Gathering data using API...
Getting page 183 of 183: https://python.zgulde.net/api/v1/sales?page=183

        item  sale_amount                      sale_date  sale_id  store
0          1         13.0  Tue, 01 Jan 2013 00:00:00 GMT        1      1
1          1         11.0  Wed, 02 Jan 2013 00:00:00 GMT        2      1
2          1         14.0  Thu, 03 Jan 2013 00:00:00 GMT        3      1
3          1         13.0  Fri, 04 Jan 2013 00:00:00 GMT        4      1
4          1         10.0  Sat, 05 Jan 2013 00:00:00 GMT        5      1
...      ...          ...                            ...      ...    ...
912995    50         63.0  Wed, 27 Dec 2017 00:00:00 GMT   912996     10
912996    50         59.0  Thu, 28 Dec 2017 00:00:00 GMT   912997     10
912997    50         74.0  Fri, 29 Dec 2017 00:00:00 GMT   912998     10
912998    50         62.0  Sat, 30 Dec 2017 00:00:00 GMT   912999     10
912999    50         82.0  Sun, 31 Dec 2017 00:00:00 GMT   913000     10

[913000 rows x 5 columns]

## Exercises 4, 5

In [28]:
def get_merged_data(use_cache=True):
    '''
    This function takes in no arguments. It firsts checks if 'merged_data.csv' exists, and if does, it returns a dataframe
    using this file. If the file does not exist it gathers the data using an API, creates a dataframe and caches it as 
    as a .csv file, then returns the dataframe.
    '''
    filename = 'merged_data.csv'

    #Check for the csv cache
    if os.path.isfile(filename) and use_cache:
        print('Using cached csv...')
        return pd.read_csv(filename)
    
    else:
        #Get items data
        items = get_items()
        #Get stores data
        stores = get_stores()
        #Get sales data
        sales = get_sales()
        
        #Merge into a singe dataframe
        #First rename columns in stores in order to correctly merge
        sales = sales.rename(columns={'store':'store_id', 'item':'item_id'})
        
        #First merging stores and sales
        df = pd.merge(sales, stores, how='left', on='store_id')
        #Next merge with items
        df = pd.merge(df, items, how='left', on='item_id')
                             
        # Now cache the dataframe as a .csv
        df.to_csv('merged_data.csv', index = False)
                             
        return df

In [29]:
df = get_merged_data()

Using cached csv...
Using cached csv...
Using cached csv...

In [31]:
df.head()

,item_id,sale_amount,sale_date,sale_id,store_id,store_address,store_city,store_state,store_zipcode,item_brand,item_name,item_price,item_upc12,item_upc14
0,1,13.0,"Tue, 01 Jan 2013 00:00:00 GMT",1,1,12125 Alamo Ranch Pkwy,San Antonio,TX,78253,Riceland,Riceland American Jazmine Rice,0.84,35200264013,35200264013
1,1,11.0,"Wed, 02 Jan 2013 00:00:00 GMT",2,1,12125 Alamo Ranch Pkwy,San Antonio,TX,78253,Riceland,Riceland American Jazmine Rice,0.84,35200264013,35200264013
2,1,14.0,"Thu, 03 Jan 2013 00:00:00 GMT",3,1,12125 Alamo Ranch Pkwy,San Antonio,TX,78253,Riceland,Riceland American Jazmine Rice,0.84,35200264013,35200264013
3,1,13.0,"Fri, 04 Jan 2013 00:00:00 GMT",4,1,12125 Alamo Ranch Pkwy,San Antonio,TX,78253,Riceland,Riceland American Jazmine Rice,0.84,35200264013,35200264013
4,1,10.0,"Sat, 05 Jan 2013 00:00:00 GMT",5,1,12125 Alamo Ranch Pkwy,San Antonio,TX,78253,Riceland,Riceland American Jazmine Rice,0.84,35200264013,35200264013

## Exercise 6 -- Acquire German Open Power Data

In [39]:
df = pd.read_csv('https://raw.githubusercontent.com/jenfly/opsd/master/opsd_germany_daily.csv')
df.head()

         Date  Consumption  Wind  Solar  Wind+Solar
0  2006-01-01     1069.184   NaN    NaN         NaN
1  2006-01-02     1380.521   NaN    NaN         NaN
2  2006-01-03     1442.533   NaN    NaN         NaN
3  2006-01-04     1457.217   NaN    NaN         NaN
4  2006-01-05     1477.131   NaN    NaN         NaN

In [44]:
# Create a function that can gather this data and cache as a .csv 

def get_power_data(use_cache=True):
    '''
    This function takes in no arguments. It firsts checks if 'german_power.csv' exists, and if does, it returns a dataframe
    using this file. If the file does not exist it gathers the data using an API, creates a dataframe and caches it as 
    as a .csv file, then returns the dataframe.
    '''
    filename = 'german_power.csv'

    #Check for the csv cache
    if os.path.isfile(filename) and use_cache:
        print('Using cached csv...')
        return pd.read_csv(filename)
    
    else:
        #Gather data
        print('Gathering data from website...')
        df = pd.read_csv('https://raw.githubusercontent.com/jenfly/opsd/master/opsd_germany_daily.csv')
        
        #Cache data locally
        df.to_csv('german_power.csv', index=False)
        
        return df

In [46]:
get_power_data()

Gathering data from website...

            Date  Consumption     Wind   Solar  Wind+Solar
0     2006-01-01   1069.18400      NaN     NaN         NaN
1     2006-01-02   1380.52100      NaN     NaN         NaN
2     2006-01-03   1442.53300      NaN     NaN         NaN
3     2006-01-04   1457.21700      NaN     NaN         NaN
4     2006-01-05   1477.13100      NaN     NaN         NaN
...          ...          ...      ...     ...         ...
4378  2017-12-27   1263.94091  394.507  16.530     411.037
4379  2017-12-28   1299.86398  506.424  14.162     520.586
4380  2017-12-29   1295.08753  584.277  29.854     614.131
4381  2017-12-30   1215.44897  721.247   7.467     728.714
4382  2017-12-31   1107.11488  721.176  19.980     741.156

[4383 rows x 5 columns]

## Exercise 7

In [2]:
#Tets my py files
import acquire as aq
df2 = aq.get_merged_data()
df2.head()

Using cached csv...

,item_id,sale_amount,sale_date,sale_id,store_id,store_address,store_city,store_state,store_zipcode,item_brand,item_name,item_price,item_upc12,item_upc14
0,1,13.0,"Tue, 01 Jan 2013 00:00:00 GMT",1,1,12125 Alamo Ranch Pkwy,San Antonio,TX,78253,Riceland,Riceland American Jazmine Rice,0.84,35200264013,35200264013
1,1,11.0,"Wed, 02 Jan 2013 00:00:00 GMT",2,1,12125 Alamo Ranch Pkwy,San Antonio,TX,78253,Riceland,Riceland American Jazmine Rice,0.84,35200264013,35200264013
2,1,14.0,"Thu, 03 Jan 2013 00:00:00 GMT",3,1,12125 Alamo Ranch Pkwy,San Antonio,TX,78253,Riceland,Riceland American Jazmine Rice,0.84,35200264013,35200264013
3,1,13.0,"Fri, 04 Jan 2013 00:00:00 GMT",4,1,12125 Alamo Ranch Pkwy,San Antonio,TX,78253,Riceland,Riceland American Jazmine Rice,0.84,35200264013,35200264013
4,1,10.0,"Sat, 05 Jan 2013 00:00:00 GMT",5,1,12125 Alamo Ranch Pkwy,San Antonio,TX,78253,Riceland,Riceland American Jazmine Rice,0.84,35200264013,35200264013

In [36]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 913000 entries, 0 to 912999
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   item_id        913000 non-null  int64
 1   sale_amount    913000 non-null  float64
 2   sale_date      913000 non-null  object
 3   sale_id        913000 non-null  int64
 4   store_id       913000 non-null  int64
 5   store_address  913000 non-null  object
 6   store_city     913000 non-null  object
 7   store_state    913000 non-null  object
 8   store_zipcode  913000 non-null  int64
 9   item_brand     913000 non-null  object
 10  item_name      913000 non-null  object
 11  item_price     913000 non-null  float64
 12  item_upc12     913000 non-null  int64
 13  item_upc14     913000 non-null  int64
dtypes: float64(2), int64(6), object(6)
memory usage: 97.5+ MB

In [3]:
df3 = aq.get_power_data()
df3.head()

Using cached csv...

         Date  Consumption  Wind  Solar  Wind+Solar
0  2006-01-01     1069.184   NaN    NaN         NaN
1  2006-01-02     1380.521   NaN    NaN         NaN
2  2006-01-03     1442.533   NaN    NaN         NaN
3  2006-01-04     1457.217   NaN    NaN         NaN
4  2006-01-05     1477.131   NaN    NaN         NaN